// tslint:disable
/**
 * Skydive API
 * The Skydive REST API allows to communicate with a Skydive analyzer.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: skydive-dev@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurationParameters {
    accessToken?: string | ((name: string) => string);
    username?: string;
    password?: string;
    basePath?: string;
}

export class Configuration {
    /**
     * parameter for accessToken security
     * @param name security name
     * @memberof Configuration
     */
    accessToken?: string | ((name: string) => string);
    /**
     * parameter for basic security
     * 
     * @type {string}
     * @memberof Configuration
     */
    username?: string;
    /**
     * parameter for basic security
     * 
     * @type {string}
     * @memberof Configuration
     */
    password?: string;
    /**
     * override base path
     * 
     * @type {string}
     * @memberof Configuration
     */
    basePath?: string;

    constructor(param: ConfigurationParameters = {}) {
        this.accessToken = param.accessToken;
        this.username = param.username;
        this.password = param.password;
        this.basePath = param.basePath;
    }
}
